include:
  - project: computing/gitlab-ci-templates
    file:
      - /conda/base.yml
      - /python/build.yml
      - /python/lint.yml

stages:
  - dist
  - test
  - lint

# -- dist -------------------

tarball:
  extends:
    - .python:dist
  image: python:3
  stage: dist
  script:
    - python -m build . --sdist --outdir .

# -- test -------------------

.test:
  extends:
    - .conda:base
  variables:
    GIT_STRATEGY: none
  stage: test
  needs:
    - tarball
  before_script:
    # configure conda
    - !reference [".conda:base", before_script]
    - conda config --file ${CONDARC} --add channels conda-forge
    # take the python version from the job name suffix
    - PYTHON_VERSION=${CI_JOB_NAME#test:python}
    # create a conda environment to test in
    - conda create --name test --yes --quiet
          python=${PYTHON_VERSION}
          c-compiler
          cython
          fftw
          liblal
    - conda activate test
    # install package and its dependencies
    - python -m pip install sbank-*.tar.gz
    # install other dependencies (including those for testing)
    - tar --wildcards --strip-components 1 -xf sbank-*.tar.gz */requirements.txt
    - python -m pip install -r requirements.txt
  script:
    # run command-line script(s)
    - python -m coverage run
          --append
          --source=sbank
          $(which lalapps_cbc_sbank) --help
  after_script:
    # print coverage report
    - ${CI_PROJECT_DIR}/envs/test/bin/python -m coverage report
    - ${CI_PROJECT_DIR}/envs/test/bin/python -m coverage xml -o coverage.xml

test:python3.6:
  extends:
    - .test

test:python3.7:
  extends:
    - .test

test:python3.8:
  extends:
    - .test

# -- lint -------------------

.lint-stage:
  stage: lint

flake8:
  extends:
    - .python:flake8
    - .lint-stage
  needs: []
  allow_failure: true
