include:
  - project: computing/gitlab-ci-templates
    file:
      - /conda/base.yml
      - /python/build.yml
      - /python/lint.yml

stages:
  - dist
  - test
  - lint

# -- dist -------------------

tarball:
  extends:
    - .python:dist
  image: python:3
  stage: dist
  script:
    - python -m build . --sdist --outdir .

# -- test -------------------

.test:
  extends:
    - .conda:base
  variables:
    GIT_STRATEGY: none
    PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pip
  stage: test
  needs:
    - tarball
  before_script:
    # clean workdir (just in case)
    - rm -rfv sbank/
    # configure conda
    - !reference [".conda:base", before_script]
    - conda config --file ${CONDARC} --add channels conda-forge
    # take the python version from the job name suffix
    - PYTHON_VERSION=${CI_JOB_NAME#test:python}
    # create a conda environment to test in
    - conda create --name test --yes --quiet
          python=${PYTHON_VERSION}
          c-compiler
          cython
          fftw
          liblal
          numpy
          pip
          setuptools
    - conda activate test
    # install package and its dependencies
    - python -m pip install sbank-*.tar.*
    # install other dependencies (including those for testing)
    - tar --wildcards --strip-components 1 -xf sbank-*.tar.* */requirements.txt
    - python -m pip install -r requirements.txt
  script:
    # run command-line script(s)
    - |
      for script in ${CONDA_PREFIX}/bin/lalapps_cbc_sbank*; do
          python -m coverage run \
              --append \
              --source=sbank \
              ${script} --help
      done
  after_script:
    # print coverage report
    - ${CI_PROJECT_DIR}/envs/test/bin/python -m coverage report
    - ${CI_PROJECT_DIR}/envs/test/bin/python -m coverage xml -o coverage.xml
    # clean unpacked conda packages (but keep the tarballs)
    - find ${CI_PROJECT_DIR}/.cache/conda/pkgs -mindepth 1 -maxdepth 1 -type d -print -exec rm -rf {} \;

test:python3.6:
  extends:
    - .test

test:python3.7:
  extends:
    - .test

test:python3.8:
  extends:
    - .test

test:python3.9:
  extends:
    - .test

# -- lint -------------------

.lint-stage:
  stage: lint

flake8:
  extends:
    - .python:flake8
    - .lint-stage
  needs: []
  allow_failure: true
